collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.3960573
color:
  saturation: 0.4408695
  brandStrength: 0.0483871
  lightness: 0.8512545
  brandColors:
    - '#004267'
    - '#BDCFD7'
    - '#A3A388'
    - '#010102'
    - '#B49242'
  rhythmicContrast: 0.6899642
layout_spectrum: 0.9390681
name: Lgwtest
