layout_spectrum: 0.2839497
typography_spectrum: 0.9768994
color:
  saturation: 0.4408695
  lightness: 0.809857
  brandStrength: 0.5428251
  rhythmicContrast: 0.7143802
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Lgwtest
